server:
  port: 8599

spring:
  application:
    name: sharding-jdbc-service
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: sub

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.huolieniao.entities    # 所有Entity别名类所在包